version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/dpkg-status-exporter
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test

workflows:
  - build
  - heroku/deploy-via-git
      requires:
        - build
      filters:
        branches:
          only: sequential-branch-filter
